"""Add mentorship plan

Revision ID: 2e7d90edf2d6
Revises: cf4c3ee4d72b
Create Date: 2026-01-28 09:19:35.675130

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e7d90edf2d6'
down_revision: Union[str, Sequence[str], None] = 'cf4c3ee4d72b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repositories', sa.Column('mentorship_plan', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('repositories', 'mentorship_plan')
    # ### end Alembic commands ###
